var map_config = {
	'default':{
		'bordercolor':'#9CA8B6', //inter-state borders
		'lakescolor':'#66CCFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'namescolor':'#666666', //color of the abbreviations 
		'namesShadowColor':'#666666', //tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'url':'#', //Goto URL
		'target':'_self', //open link in new window:_blank, open in current window:_self
		'upcolor':'#BBBBBB', //state's color when page loads
		'overcolor':'#d17547', //state's color when mouse hover
		'downcolor':'#601b28',//state's color when mouse clicking
		'enable':false,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'url':'/alaska_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',
		'url':'/arizona_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'url':'/california_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'url':'/colorado_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'url':'/idaho_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'url':'/minnesota_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'url':'/montana_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'url':'/nevada_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'url':'/new_mexico_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'url':'/new_york_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'url':'/oregon_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'url':'/pennsylvania_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'url':'/utah_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT (NEW ENGLAND)',
		'url':'/new_england',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'url':'/washington_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'url':'/wyoming_bha',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_51':{
		'namesId':'AB',
		'name': 'ALBERTA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_52':{
		'namesId':'BC',
		'name': 'BRITISH COLUMBIA',
		'url':'/bc_canada',
		'target':'_self',
		'upcolor':'#EBECED',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':true,
	},
	'map_53':{
		'namesId':'MB',
		'name': 'MANITOBA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_54':{
		'namesId':'NB',
		'name': 'NEW BRUNSWICK',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_55':{
		'namesId':'NL',
		'name': 'NEWFOUNDLAND AND LABRADOR',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_56':{
		'namesId':'NT',
		'name': 'NORTHWEST TERRITORIES',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_57':{
		'namesId':'NS',
		'name': 'NOVA SCOTIA',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_58':{
		'namesId':'NU',
		'name': 'NUNAVUT',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_59':{
		'namesId':'ON',
		'name': 'ONTARIO',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_60':{
		'namesId':'PE',
		'name': 'PRINCE EDWARD ISLAND',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_61':{
		'namesId':'QC',
		'name': 'QUEBEC',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_62':{
		'namesId':'SK',
		'name': 'SASKATCHEWAN',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
	'map_63':{
		'namesId':'YT',
		'name': 'YUKON',
		'url':'#',
		'target':'_self',
		'upcolor':'#BBBBBB',
		'overcolor':'#d17547',
		'downcolor':'#601b28',
		'enable':false,
	},
}
